<a href="https://colab.research.google.com/github/adnanhilal/H.W2/blob/master/Hilal_otto_group_product_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data download and preparing 

In [0]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectKBest
from sklearn.linear_model import LogisticRegression

In [0]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error

In [0]:
from sklearn import preprocessing 
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [0]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [0]:
import warnings
warnings.filterwarnings('ignore')


In [0]:
data_url="https://raw.githubusercontent.com/adnanhilal/H.W2/master/train.csv"

In [0]:
producttrain = pd.read_csv(data_url)

In [0]:
producttrain.columns 

Index(['id', 'feat_1', 'feat_2', 'feat_3', 'feat_4', 'feat_5', 'feat_6',
       'feat_7', 'feat_8', 'feat_9', 'feat_10', 'feat_11', 'feat_12',
       'feat_13', 'feat_14', 'feat_15', 'feat_16', 'feat_17', 'feat_18',
       'feat_19', 'feat_20', 'feat_21', 'feat_22', 'feat_23', 'feat_24',
       'feat_25', 'feat_26', 'feat_27', 'feat_28', 'feat_29', 'feat_30',
       'feat_31', 'feat_32', 'feat_33', 'feat_34', 'feat_35', 'feat_36',
       'feat_37', 'feat_38', 'feat_39', 'feat_40', 'feat_41', 'feat_42',
       'feat_43', 'feat_44', 'feat_45', 'feat_46', 'feat_47', 'feat_48',
       'feat_49', 'feat_50', 'feat_51', 'feat_52', 'feat_53', 'feat_54',
       'feat_55', 'feat_56', 'feat_57', 'feat_58', 'feat_59', 'feat_60',
       'feat_61', 'feat_62', 'feat_63', 'feat_64', 'feat_65', 'feat_66',
       'feat_67', 'feat_68', 'feat_69', 'feat_70', 'feat_71', 'feat_72',
       'feat_73', 'feat_74', 'feat_75', 'feat_76', 'feat_77', 'feat_78',
       'feat_79', 'feat_80', 'feat_81', 'feat_82', 'fe

In [0]:
#producttrain


In [0]:
producttrain.target.replace(('Class_1','Class_2','Class_3','Class_4','Class_5','Class_6','Class_7','Class_8','Class_9'),
                        (1,2,3,4,5,6,7,8,9), inplace=True)

In [0]:
X = producttrain.drop('target', axis=1)
Y = producttrain['target']

In [0]:
#X

In [0]:
scaler = preprocessing.StandardScaler().fit(X)

In [0]:
scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

In [0]:
X=scaler.transform(X)

In [0]:
X

array([[-1.73202282,  0.40209324, -0.21010603, ..., -0.12951551,
        -0.38693809, -0.10496314],
       [-1.73196683, -0.25350808, -0.21010603, ..., -0.12951551,
        -0.38693809, -0.10496314],
       [-1.73191085, -0.25350808, -0.21010603, ..., -0.12951551,
        -0.38693809, -0.10496314],
       ...,
       [ 1.73191085, -0.25350808, -0.21010603, ..., -0.12951551,
        -0.38693809, -0.10496314],
       [ 1.73196683,  0.40209324, -0.21010603, ...,  1.33702606,
         9.792457  , -0.10496314],
       [ 1.73202282, -0.25350808, -0.21010603, ..., -0.12951551,
         1.64894093, -0.10496314]])

In [0]:
Xtrain, Xtest, Ytrain, Ytest = train_test_split(X, Y, test_size = 0.3, random_state=50)

# Train a Multi-layer Perceptron (MLP)

In [0]:
from sklearn.neural_network import MLPClassifier
mlcp = MLPClassifier(hidden_layer_sizes=(100, ), activation='relu',
alpha=0.0001,batch_size='auto', learning_rate_init=0.001, max_iter=200, shuffle=True, random_state=None,
tol=0.0001, warm_start=False,early_stopping=True, validation_fraction=0.1,
beta_1=0.9,beta_2=0.999, epsilon=1e-08).fit(Xtrain, Ytrain)

In [0]:
print('accuracy for train MLP:', accuracy_score(Ytrain, mlcp.predict(Xtrain)))
print('accuracy for test MLP:', accuracy_score(Ytest, mlcp.predict(Xtest)))

accuracy for train MLP: 0.9929814840467286
accuracy for test MLP: 0.9752208575737987


In [0]:
y_predmlcp=mlcp.predict(Xtest)
confusion_matrix(Ytest, y_predmlcp)

array([[ 551,   17,    0,    0,    0,    0,    0,    0,    0],
       [   8, 4744,   61,    1,    0,    0,    0,    0,    0],
       [   0,   59, 2312,   11,    1,    0,    0,    0,    0],
       [   0,    0,   52,  740,    5,    4,    0,    0,    0],
       [   0,    0,    0,    7,  873,    1,    0,    0,    0],
       [   1,    0,    0,    8,    5, 4134,   39,   19,    0],
       [   0,    0,    0,    1,    0,   21,  805,   35,    0],
       [   0,    0,    0,    0,    0,   16,   29, 2478,   18],
       [   0,    0,    0,    0,    0,    0,    3,   38, 1467]])

# 	K-Nearest Neighbours

In [0]:
knnclass = KNeighborsClassifier(n_neighbors=3, p=2)
knn = knnclass.fit(Xtrain, Ytrain)

In [0]:
#print('accuracy for train knn:', accuracy_score(Ytrain, knn.predict(Xtrain)))
#print('accuracy for test knn:', accuracy_score(Ytest, knn.predict(Xtest)))
#KNN take very long time to calculate the accuracy

In [0]:
#y_predknn=knn.predict(Xtest)
#confusion_matrix(Ytest, y_predknn)

# Decision Tree Classifier

In [0]:
tree = DecisionTreeClassifier(max_leaf_nodes=9,max_depth=10).fit(Xtrain, Ytrain)

In [0]:
print('accuracy for train tree:', accuracy_score(Ytrain, tree.predict(Xtrain)))
print('accuracy for test Tree:', accuracy_score(Ytest, tree.predict(Xtest)))

accuracy for train tree: 1.0
accuracy for test Tree: 0.999892264598147


In [0]:
y_predtree=tree.predict(Xtest)
confusion_matrix(Ytest, y_predtree)

array([[ 568,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0, 4814,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0, 2383,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,  801,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,  881,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0, 4206,    0,    0,    0],
       [   0,    0,    0,    0,    0,    1,  861,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0, 2540,    1],
       [   0,    0,    0,    0,    0,    0,    0,    0, 1508]])

# Support Vector Machines

In [0]:
svc = SVC(C=20, max_iter=150, degree=9 ).fit(Xtrain, Ytrain)

In [0]:
print('Accuracy as traning for Support Vector Machine:',accuracy_score(Ytrain, svc.predict(Xtrain)))
print('Accuracy as test for Support Vector Machine:',accuracy_score(Ytest, svc.predict(Xtest)))

Accuracy as traning for Support Vector Machine: 0.8486632497575841
Accuracy as test for Support Vector Machine: 0.8400667959491489


In [0]:
#from sklearn.model_selection import GridSearchCV
#svc = SVC()
#parameters = {'C': (13,20), 'max_iter': (100,150)}
#gscvsvc = GridSearchCV(estimator = svc, param_grid = parameters, n_jobs=-1,cv=5, )
#gscvsvc.fit(Xtrain, Ytrain)

In [0]:
#gscvsvc.score(Xtest, Ytest)

In [0]:
#gscvsvc.score(Xtrain, Ytrain)

In [0]:
#gscvsvc.best_params_

In [0]:
#print('Accuracy as test for Support Vector Machine:',gscvsvc.score(X_test, y_test))

# Random Forest

In [0]:
import seaborn as sns
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.ensemble import BaggingClassifier, BaggingRegressor
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier
from sklearn.datasets import make_circles
from sklearn.model_selection import train_test_split


In [0]:
rf = RandomForestClassifier(n_estimators=35).fit(Xtrain, Ytrain)

In [0]:
print('accuracy for train randomtree:', accuracy_score(Ytrain, rf.predict(Xtrain)))
print('accuracy for test randomtree:', accuracy_score(Ytest, rf.predict(Xtest)))

accuracy for train randomtree: 1.0
accuracy for test randomtree: 0.9926201249730662


In [0]:
y_predrf=rf.predict(Xtest)

In [0]:
y_predrf

array([6, 8, 9, ..., 3, 9, 3])

In [0]:
confusion_matrix(Ytest, y_predrf)

array([[ 562,    1,    0,    0,    0,    5,    0,    0,    0],
       [   0, 4813,    0,    0,    0,    1,    0,    0,    0],
       [   0,    3, 2378,    0,    0,    0,    2,    0,    0],
       [   0,    0,   10,  777,    3,    8,    2,    0,    1],
       [   0,    0,    1,    8,  872,    0,    0,    0,    0],
       [   0,    0,    2,    4,    0, 4171,   24,    1,    4],
       [   0,    0,    5,    7,    2,   24,  820,    4,    0],
       [   0,    0,    0,    0,    0,    1,    4, 2536,    0],
       [   0,    0,    0,    0,    1,    1,    2,    6, 1498]])

#  Gradient Boosting Classifier

In [0]:
from sklearn.ensemble import GradientBoostingClassifier
clf = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0,max_depth=1, random_state=0).fit(Xtrain, Ytrain)

In [0]:
clf.score(Xtrain, Ytrain) 

1.0

In [0]:
clf.score(Xtest, Ytest) 

0.999892264598147

In [0]:
y_predclf=clf.predict(Xtest)

In [0]:
confusion_matrix(Ytest, y_predclf)

array([[ 568,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0, 4814,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0, 2383,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,  801,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,  881,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0, 4206,    0,    0,    0],
       [   0,    0,    0,    0,    0,    1,  861,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0, 2540,    1],
       [   0,    0,    0,    0,    0,    0,    0,    0, 1508]])

# comparison 

1- KNN take very long time to calculate the accuracy

2- best accuracies comes from Decision Tree Classifier,  Gradient Boosting Classifier, and Random Forest.

3- Support Vector Machines showes the lowest accuraci, it could be enhanced by gride search but it takes time 